---
pool_regex: "{{ satellite_subscription_pool_regex }}"
#poolid: "{{ satellite_subscription_poolid }}"
repos: "{{ satellite_repos }}"

product_config:
  - product: "Red Hat Enterprise Linux Server"
    basearch: x86_64
    repos:
      - name: "Red Hat Enterprise Linux 7 Server (RPMs)"
        releasever: 7Server
      - name: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"
      - name: "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"
        releasever: 7Server
      - name: "Red Hat Enterprise Linux 7 Server (Kickstart)"
        releasever: "7.2"
      - name: "Red Hat Satellite Tools 6.2 (for RHEL 7 Server) (RPMs)"
#need manifest WITH satellite
#  - product: Red Hat Satellite
#    basearch: x86_64
#    repos:
#      - name: Red Hat Satellite 6.2 (for RHEL 7 Server) (RPMs)
#        releasever: 7Server
  - product: Red Hat Software Collections for RHEL Server
    basearch: x86_64
    repos:
      - name: Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server
        releasever: 7Server
  - product: Red Hat Enterprise Virtualization
    basearch: x86_64
    repos:
     # - name: Red Hat Enterprise Virtualization Management Agents for RHEL 7 (RPMs)
     #   releasever: 7Server
     # - name: Red Hat Enterprise Virtualization Manager 3.6 (RPMs)
      - name: Red Hat Virtualization 4 Management Agents for RHEL 7 (RPMs)
        releasever: 7Server
      - name: Red Hat Virtualization Manager 4.0 (RHEL 7 Server) (RPMs)

lifecycle_environments:
  - name: 'PROD'
    prior: 'Library'
    description: 'Production'
    label: 'production'

content_config:
  - content_view: "CV-OS-RHEL7-SERVER"
    content:
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Satellite Tools 6.2 for RHEL 7 Server RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server"
    host_collection: "RHEL7"
    override: "rhel-7-server-satellite-tools-6.2-rpms"
    activation_key_subscription_regex: "{{ rhel_subscription_pool_regex }}"

  - content_view: "CV-RHEV-MANAGER"
    content:
      - product: "Red Hat Enterprise Virtualization"
        repository: "Red Hat Enterprise Virtualization Manager 3.6 RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Satellite Tools 6.1 for RHEL 7 Server RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server - Supplementary RPMs x86_64 7Server"
    override: "rhel-6-server-satellite-tools-6.2-rpms"
    host_collection: "RHEVM"
    activation_key_subscription_regex: "{{ rhev_subscription_pool_regex }}"

  - content_view: "CV-RHEV-HYPERVISOR"
    content:
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Satellite Tools 6.2 for RHEL 7 Server RPMs x86_64"
      - product: "Red Hat Enterprise Virtualization"
        repository: "Red Hat Enterprise Virtualization Management Agents for RHEL 7 RPMs x86_64 7Server"
    override: "rhel-7-server-satellite-tools-6.2-rpms"
    host_collection: "RHEVH"
    activation_key_subscription_regex: "{{ rhev_subscription_pool_regex }}"
