---
pool_regex: "{{ satellite_subscription_pool_regex }}"
#poolid: "{{ satellite_subscription_poolid }}"
# repos to install Satellite Server itself
repos: "{{ satellite_repos }}"

product_config:
  - product: "Red Hat Enterprise Linux Server"
    basearch: x86_64
    repos:
      - name: "Red Hat Enterprise Linux 7 Server (RPMs)"
        releasever: 7Server
      - name: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"
        releasever: 7Server
      - name: "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"
        releasever: 7Server
      - name: "Red Hat Enterprise Linux 7 Server - RH Common (RPMs)"
        releasever: 7Server
      - name: "Red Hat Enterprise Linux 7 Server (Kickstart)"
        releasever: "7.2"
      - name: "Red Hat Satellite Tools 6.2 (for RHEL 7 Server) (RPMs)"
#need manifest WITH satellite
#  - product: Red Hat Satellite
#    basearch: x86_64
#    repos:
#      - name: Red Hat Satellite 6.2 (for RHEL 7 Server) (RPMs)
#        releasever: 7Server
  - product: Red Hat Software Collections for RHEL Server
    basearch: x86_64
    repos:
      - name: Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server
        releasever: 7Server
  - product: Red Hat Enterprise Virtualization
    basearch: x86_64
    repos:
      - name: Red Hat Virtualization 4 Management Agents for RHEL 7 (RPMs)
        releasever: 7Server
      - name: Red Hat Virtualization Manager 4.0 (RHEL 7 Server) (RPMs)
  - product: Red Hat Virtualization Host
    basearch: x86_64
    repos:
      - name: Red Hat Virtualization Host 7 (RPMs)
  - product: Red Hat Gluster Storage Server for On-premise
    basearch: x86_64
    repos:
      - name: Red Hat Gluster Storage 3.1 Server (RPMs)
        releasever: 7Server
      - name: Red Hat Gluster Storage 3.1 Samba (for RHEL 7 Server) (RPMs)
        releasever: 7Server
      - name: Red Hat Gluster Storage 3.1 NFS (RPMs)
        releasever: 7Server
  - product: Red Hat Gluster Storage Nagios Server
    basearch: x86_64
    repos:
      - name: Red Hat Gluster Storage 3.1 Nagios (RPMs)
        releasever: 7Server
  - product: Red Hat Gluster Storage Management Console for RHEL Server
    basearch: x86_64
    repos:
      - name: Red Hat Gluster Storage 3.1 Console (RPMs)
        releasever: 7Server

# eventluell noetig....
   #- product: Red Hat Storage Native Client for RHEL 7 (RPMs)
   # basearch: x86_64
   # repos:
   #    - name: Red Hat Storage Native Client for RHEL 7 RPMs
   #      releasever: 7Server


lifecycle_environments:
  - name: 'PROD'
    prior: 'Library'
    description: 'Production'
    label: 'production'

content_config:
  - content_view: "all_and_newest"
    content:
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server (RPMs)"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server - RH Common (RPMs)"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server (Kickstart)"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Satellite Tools 6.2 (for RHEL 7 Server) (RPMs)"
#need manifest WITH satellite
#      - product: Red Hat Satellite
#        repository: Red Hat Satellite 6.2 (for RHEL 7 Server) (RPMs)
      - product: Red Hat Software Collections for RHEL Server
        repository: Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server
      - product: Red Hat Enterprise Virtualization
        repository: Red Hat Virtualization 4 Management Agents for RHEL 7 (RPMs)
      - product: Red Hat Enterprise Virtualization
        repository: Red Hat Virtualization Manager 4.0 (RHEL 7 Server) (RPMs)
      - product: Red Hat Virtualization Host
        repository: Red Hat Virtualization Host 7 (RPMs)
      - product: Red Hat Gluster Storage Server for On-premise
        repository: Red Hat Gluster Storage 3.1 Server (RPMs)
      - product: Red Hat Gluster Storage Server for On-premise
        repository: Red Hat Gluster Storage 3.1 Samba (for RHEL 7 Server) (RPMs)
      - product: Red Hat Gluster Storage Server for On-premise
        repository: Red Hat Gluster Storage 3.1 NFS (RPMs)
      - product: Red Hat Gluster Storage Nagios Server
        repository: Red Hat Gluster Storage 3.1 Nagios (RPMs)
      - product: Red Hat Gluster Storage Management Console for RHEL Server
        repository: Red Hat Gluster Storage 3.1 Console (RPMs)
# eventluell noetig....
#      - product: Red Hat Storage Native Client for RHEL 7 (RPMs)
#        repository: Red Hat Storage Native Client for RHEL 7 RPMs
    host_collection: "RHEL7"
    override: "rhel-7-server-satellite-tools-6.2-rpms"
    activation_key_subscription_regex: "{{ rhel_subscription_pool_regex }}"
