---
- name: check whether satellite installation did run before
  stat:
    path: /var/log/katello-installer/katello-installer.log
  register: katello_installer_log


# i will run the upgrade if satellite is allready installed and if yum updated

- name: update satellite installation
  shell: satellite-installer --upgrade
  when: yum_update is defined and yum_update.changed and katello_installer_log.stat.exists is defined and katello_installer_log.stat.exists == True
