---
- name: add services to firewall
  firewalld: service="{{ item }}" permanent=true state=enabled immediate=true
  with_items:
    - RH-Satellite-6 
    - dhcp
    - dns
    - tftp

- name: add port to firewall
  firewalld: port="{{ item }}" permanent=true state=enabled immediate=true
  with_items:
    - 8000/tcp
    - 67/udp
    - 68/udp
    # - 69/udp tftp
    - 80/tcp
    - 443/tcp
    - 5647/tcp
    - 8140/tcp


