---
- name: set resolv.conf to upstream_dns
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  vars:
    dns_nameservers: "{{ upstream_dns }}"

# set short and full hostname in the /etc/hosts due our lack of DNS here
- name: add entry to /etc/hosts
  lineinfile: dest=/etc/hosts line="{{ mgt_ip }} {{ hostname }}  {{ inventory_hostname_short }} "




