name: gluster22
mac: 00:1F:29:E6:B4:84
type: gluster
dc: right
fqdn: gluster22.example.com.  
ipaddress: 172.16.20.204 
reverse: 204.20.16.172.in-addr.arpa.
ilo_name: gluster22-ilo
ilo_ip: 172.16.10.204
ilo_mac: 00:1f:29:e6:b4:86 
ilo_reverse: 204.10.16.172.in-addr.arpa.
