= AsciiDoctor Based Engagement Journal

For years Ive used the official Libre Office template to create my journals and customer documentation, and while the results are fine, its always felt overly complex. I really wanted to just write in markdown and create a PDF to give to the customer.

Now I can, thanks to asciidoctor. You actually write in asciidoctor not markdown, but its good enough for me.

To get started, take a look at INSTALL.adoc

== What is AsciiDoc?
AsciiDoc is two things:

* A mature, plain-text writing format for authoring notes, articles, documentation, books, ebooks, web pages, slide decks, blog posts, man pages and more.

* A text processor and toolchain for translating AsciiDoc documents into various formats (called backends), including HTML, DocBook, PDF and ePub[2].

AsciiDoc belongs to the family of lightweight markup languages, the most renowned of which is Markdown. AsciiDoc stands out from this group because it supports all the structural elements necessary for drafting articles, technical manuals, books, presentations and prose. In fact, it’s capable of meeting even the most advanced publishing requirements and technical semantics.
