
- name: get locations for dnsdomain
  shell: "hammer --csv location list | awk -F, 'NR==2 { print $1 }'"
  register: current_location
  changed_when: false


- name: update dnsdomain
  command: "hammer domain update --organizations '{{ organization }}' --location-ids {{ current_location.stdout }} --dns {{ mgt_hostname }} --name {{ dns_domain }}"
