- name: get current organizations 
  shell: "hammer --csv organization list | awk -F, 'NR>1 {print $2}'"
  register: current_organizations
  changed_when: false

- name: create organization
  shell: hammer organization create --name "{{ organization }}" 
  register: orgs
  when: organization not in current_organizations.stdout_lines

