---
- hosts: jump
  vars_files:
    - vars/secret.yml
  remote_user: root
  gather_facts: false
  roles:
    - install_satellite 
    - backup_satellite
    - mgt_satellite 

 ## FIXME:
 ## missing:
   # create ssh-key as root
   # deploy ssh-keys to all servers
   # setup dhcp for ilo-LAN


