---
- hosts: jump
  vars_files:
    - vars/secret.yml
  remote_user: root
  gather_facts: false
  roles:
    - role: install_satellite
      tags:
        - install
    - role: backup_satellite
      tags: 
        - backup
    - role: mgt_satellite 
      tags: 
        - configure

 ## FIXME:
 ## missing:
   # create ssh-key as root
   # deploy ssh-keys to all servers
   # setup dhcp for ilo-LAN


