# reboot a system
# from http://stackoverflow.com/questions/23877781/how-to-wait-for-server-restart-using-ansible/28070759#28070759

- hosts: "{{ server }}"
  remote_user: root
  gather_facts: False 
  tasks:
   - name: Shutdown a server
     shell: echo "Rebooting $hostname"
     notify:
      - Shutdown server
      - Wait for server to switch off


  handlers:
    - name: Shutdown server
      shell: sleep 2 && shutdown now "Shutdown triggered by Ansible"
      async: 1
      poll: 0
      ignore_errors: true
    - name: Wait for server to switch off
      raw: power 
      register: power
      delegate_to: "{{ inventory_hostname }}-ilo"
      until: power.stdout.find("Off") != -1
      retries: 5
      delay: 30
  
